version: '3.7'
services:
  dashboard:
    build: ./dashboard
    image: ventilators-dashboard
    restart: always
    container_name: ventilators-dashboard
    depends_on:
      - tsdb
    ports:
      - 3000:3000
    environment:
      GF_PATHS_CONFIG: /dashboard/grafana.ini
      GF_PATHS_PROVISIONING: /dashboard/provisioning
      GF_INSTALL_PLUGINS: yesoreyeram-boomtable-panel 1.3.0
      GF_TSDB_USER: ventilators
      GF_TSDB_PASSWORD: ventilators
      GF_SECURITY_ADMIN_USER: admin

  dashboard-initializer:
    image: ventilators-dashboard
    entrypoint: ["/dashboard/set_home.sh"]
    container_name: ventilators-dashboard-initializer
    depends_on:
      - dashboard
    restart: on-failure
    environment:
      DASHBOARD_INITIALIZER_API_URL: http://dashboard:3000
      DASHBOARD_INITIALIZER_HOME_DASHBOARD_ID: 1
      DASHBOARD_INITIALIZER_ADMIN_USER: admin
      DASHBOARD_INITIALIZER_ADMIN_PASSWORD: soyeladmin

  tsdb:
    image: influxdb:1.7-alpine
    container_name: ventilators-tsdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - time-series-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: ventilators
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: ventilators
      INFLUXDB_USER_PASSWORD: ventilators

  receiver:
    build: ./receiver
    container_name: ventilators-receiver
    restart: always
    depends_on:
      - tsdb
    environment:
      RECEIVER_TSDB_HOST: tsdb
      RECEIVER_TSDB_PORT: 8086
      RECEIVER_TSDB_DB: ventilators
      RECEIVER_TSDB_USER: ventilators
      RECEIVER_TSDB_PASSWORD: ventilators
    ports:
      - 5000:5000

  watchdog:
    build: ./watchdog
    container_name: ventilators-watchdog
    depends_on:
      - tsdb
    restart: on-failure
    environment:
      WATCHDOG_TSDB_HOST: tsdb
      WATCHDOG_TSDB_PORT: 8086
      WATCHDOG_TSDB_DB: ventilators
      WATCHDOG_TSDB_USER: ventilators
      WATCHDOG_TSDB_PASSWORD: ventilators
      WATCHDOG_DELTA: 30
      WATCHDOG_PERIOD: 15

volumes:
  time-series-data:
