version: '3.7'
services:
  dashboard:
    volumes:
      - ./dashboard:/dashboard

  dashboard-initializer:
    volumes:
      - ./dashboard:/dashboard

  receiver:
    command: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
    environment:
      FLASK_APP: receiver.py
      FLASK_ENV: development
    volumes:
      - ./receiver:/app

  watchdog:
    volumes:
      - ./watchdog:/app

  ventilators-mock:
    build: ./ventilators-mock
    image: ventilators-mock
    container_name: ventilators-mock
    command: ["./ventilators-mock.sh", "--count", "25", "--exclude", "1", "--exclude", "2"]
    restart: always
    depends_on:
      - receiver
    environment:
      VENTILATORS_MOCK_RECEIVER_HOST: receiver
      VENTILATORS_MOCK_RECEIVER_PORT: 5000
